name = "mideapage-ts"
main = "src/index.ts"
compatibility_date = "2025-06-04"
account_id = "1e1f534910c36b2304b1e4fdca78a03b" # 替换为你的实际 account_id (如果不同)

# --- D1 数据库绑定 ---
[[d1_databases]]
binding = "DB_MOVIES"  
database_name = "movies_database_d1"
database_id = "1a6374b8-39fa-4a5d-9749-f9c3bdbaf108"

[[d1_databases]]
binding = "DB_MANGA"
database_name = "manga_date_d1"
database_id = "4eb7182f-7cea-420e-903a-f336cf95f6c2"

# --- R2 存储桶绑定 ---
[[r2_buckets]]
binding = "MANGA_BUCKET"
bucket_name = "manga"

[[r2_buckets]]
binding = "MOVIES_ASSETS_BUCKET"
bucket_name = "movies"

[[r2_buckets]]
binding = "STATIC_FILES_BUCKET"
bucket_name = "static"



# --- 环境变量 / 密钥 ---
[vars]
LOGIN_CODE = "114514"
IS_LOCAL_DEV = "false" # 生产环境设置为 "false", 本地开发在 .dev.vars 中设置为 "true"

# R2 路径前缀 (这些必须与你在 R2 中的文件组织方式匹配)
MANGA_R2_BASE_PREFIX = "manga/manga"
MOVIE_ASSETS_R2_BASE_PREFIX = "movies/movies"
ACTOR_THUMBS_R2_SUBFOLDER = "actors_photo/演员图片/文件夹下/"

# 如果使用电影流媒体功能:
MOVIE_STREAMS_R2_PREFIX = "path/to/video/files/prefix" # !!! 替换: STREAMS_BUCKET 中视频文件的前缀 (例如 "streams" 或空) !!!

# 注意: SESSION_SECRET_KEY 应该通过 `wrangler secret put SESSION_SECRET_KEY` 设置

[observability.logs] # `observability` 块应该只包含 Cloudflare 定义的配置
enabled = true

# 本地开发时，在项目根目录创建 .dev.vars 文件:
# IS_LOCAL_DEV = "true"
# LOGIN_CODE = "114514"
# SESSION_SECRET_KEY = "a-very-strong-secret-key-for-local-dev"
# MANGA_R2_BASE_PREFIX = "manga/manga"
# MOVIE_ASSETS_R2_BASE_PREFIX = "movies/movies"
# ACTOR_THUMBS_R2_SUBFOLDER = "actors_photo/演员图片/文件夹下/"
# MOVIE_STREAMS_R2_PREFIX = "local/dev/streams/prefix"
